blog/urls.py
from django.urls import path
from . import views
# Nombre blog es una variable que hace referencia a cada post
app_name = 'blog'

urlpatterns = [
    path('', views.posts, name='posts'),
    path('<int:post_id>', views.post_detail, name='post_detail'),
]

mi_porfolio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('porfolio.urls')),
    path('blog/', include('blog.urls')),
    
]

porfolio/urls.py
from django.urls import path
from . import views


from django.conf import settings
from django.contrib.staticfiles.urls import static

urlpatterns = [
    path('', views.inicio, name='inicio'),
    path('home', views.home, name='home'),
    path('contacto', views.contacto, name='contacto'),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

blog/models.py
from django.db import models
from datetime import date

# Create your models here.
class Post(models.Model):
    titulo = models.CharField(max_length=100)
    descripcion=models.TextField()
    imagen = models.ImageField(upload_to='blog/imagen')
    fecha = models.DateField()
    
    def __str__(self):
        return 'Post ' + str(self.id) + ': ' +  self.titulo
    
    def delete(self, using=None, keep_parents=False):
        self.imagen.storage.delete(self.imagen.name)
        super().delete()

porfolio/models.py
from distutils.command.upload import upload
from tkinter import image_names
from django.db import models
from django.db.models.fields import CharField, URLField
from django.db.models.fields.files import ImageField


# Create your models here.
class Proyecto(models.Model):
    titulo = CharField(max_length=100)
    descripcion = CharField(max_length=250)
    imagen = ImageField(upload_to='porfolio/imagen/')
    url = URLField(blank=True)
    
    def __str__(self):
        return 'Proyecto ' + str(self.id) + ': ' + self.titulo 
    
    def delete(self, using=None, keep_parents=False):
        self.imagen.storage.delete(self.imagen.name)
        super().delete()

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post
# Create your views here.

def posts(request):
    posts = Post.objects.all()
    return render(request, 'posts.html', {'posts': posts})

def post_detail(request, post_id): 
    #get_object_or_404-> Toma un modelo y luego una primary key 
    post = get_object_or_404(Post, pk=post_id)  
    return render(request, 'post_detail.html', {'post': post})

porfolio/views.py
from django.shortcuts import render
from .models import Proyecto

# Create your views here.

#Vista INICIO
def inicio(request):
    return render(request, 'inicio.html')

#Vista HOME
def home(request):
    proyectos = Proyecto.objects.all()
    return render(request, 'home.html', {'proyectos': proyectos})

#Vista CONTACTO
def contacto(request):
    return render(request, 'contacto.html')

blog/templates/post_detail.html
{% extends 'componentes/body.html' %}

{% block titulo %} Post {{post.id}} {% endblock %}

{% block contenido %}
<div class="text-center">
    <h2 class="display-6" style="display:inline-block"> 🧐{{post.titulo}} </h2>
    <h3 class="h5 lead text-muted text-end ms-3" style="display:inline-block">{{post.fecha | date:'M d Y'}} 📅</h3>
    <br>
    <div class="post-detail">
        <img class="izquierda" src="{{post.imagen.url}}" alt="Imagen sobre {{p.titulo}}">
        <p class="text-start mt-3">{{post.descripcion | safe }}</p>
    </div>
            
</div>

{% endblock %}

blog/templates/posts.html
{% extends 'componentes/body.html' %}

{% block titulo %} Blog {% endblock %}

{% block contenido %}
    {% for p in posts %}
    <div class="card card-body mb-3 card-blog">
        <div class="row">
            <div class="col-3">
                <img class="card-img-fluid" src="{{p.imagen.url}}" width="200px" height="200px" alt="Imagen sobre {{p.titulo}}">
            </div>
            <div class="col-9">
                <h4 class="text-end text-muted lead">{{p.fecha | date:'M d Y'}} 📅</>
                <h4 class="card-title">{{p.titulo | upper }}</h4>
                <p class="card-text lead">{{p.descripcion | striptags | truncatechars:100 }}</p>
                <a class="btn btn-black bg-dark rounded-3 text-light" href="{% url 'blog:post_detail' p.id %}"> 🧐 Leer más!</a>
            </div>
        </div>
    </div>
    {% endfor %}
{% endblock %}

porfolio/templates/componentes/body.html
{% load static %}
<!doctype html>
<html lang="en">
    <head>
        <!--Seccion TITULO-->
        <title>{% block title%} {% endblock %}</title>

        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        
        <!-- Bootstrap CSS v5.0.2 -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"  integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        
        <!-- Bootstrap iniconos -->
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css"
            integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
        
        <!--Estilos CSS-->
        <link rel="stylesheet" href="{% static 'style.css' %}">

    </head>

    <body> 
        <!--Seccion NAVBAR-->  
        {% include 'componentes/navbar.html' %}

        <!--Seccion COTENENDOR-->
        <div class="container">
            <div class="row">
                <div class="col-12">
                    {% block contenido %} {% endblock %}
                </div>
            </div>
        </div>

        <!--Seccion FOOTER-->
        {% include 'componentes/footer.html' %}


        <!-- Bootstrap JavaScript Libraries -->
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    </body>
</html>

porfolio/templates/componentes/footer.html
{% load static %}

<!--Seccion FOOTER-->
<footer class="text-center" style="margin-top:20px; color:rgb(0, 0, 0); background-color: rgb(22, 153, 92)">
    <!-- Grid container -->
    <div class="container p-4 pb-3 " >
        <!-- Section: Social media -->
        <section>
            <!-- Linkedin -->
            <a class="btn  btn-floating m-2" href="https://www.linkedin.com/in/cantarini-maria-sol/" role="button"
                style="border-radius:50%" target="_blank">
                <i class="fab fa-linkedin-in" style="color:rgb(0, 0, 0)"></i>
            </a>

            <!-- Github -->
            <a class="btn  btn-floating m-2" href="https://github.com/cantariniSol" role="button" style="border-radius:50%"
                target="_blank">
                <i class="fab fa-github" style="color: rgb(0, 0, 0)"></i>
            </a>
            
            <!-- Gmail -->
            <a class="btn btn-floating m-2" href="#cantarinisol@gmail.com" role="button" style="border-radius:50%"
                target="_blank">
                <i class="fab fa-google" style="color:rgb(0, 0, 0)"></i>
            </a>
        </section>
        <!-- Section: Social media -->
    </div>
    <!-- Grid container -->

    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: rgb(21, 126, 77)">
        © 2022 Copyright: Sol Cantarini
    </div>
    <!-- Copyright -->
</footer>

porfolio/templates/componentes/header.html
{% load static %}

<!--Seccion HEADER-->
<header id="header-porfolio" class="row">
    <div class="col-md-4">
        <img id="img-porfolio" src="{% static 'porfolio/porfolio.jpeg'%}" width="100%" height="100%" alt="MySelf">
    </div>
    <div class="col-md-8 my-auto">
        <section>
            <h1 class="display-6 pe-4" style="display:inline-block">Soy <strong>Sol Cantarini</strong></h1>
            <!-- Seccion REDES SOCIALES -->
            <div style="display:inline-block">
                <!-- Linkedin -->
                <a class="btn  btn-floating mb-3" href="https://www.linkedin.com/in/cantarini-maria-sol/" role="button"
                    style="border-radius:50%" target="_blank">
                    <i class="fab fa-linkedin-in" style="color:rgb(0, 0, 0)"></i>
                </a>
            
                <!-- Github -->
                <a class="btn btn-floating mb-3" href="https://github.com/cantariniSol" role="button" style="border-radius:50%"
                    target="_blank">
                    <i class="fab fa-github" style="color: rgb(0, 0, 0)"></i>
                </a>
            
                <!-- Gmail -->
                <a class="btn btn-floating mb-3" href="#cantarinisol@gmail.com" role="button" style="border-radius:50%"
                    target="_blank">
                    <i class="fab fa-google" style="color:rgb(0, 0, 0)"></i>
                </a>
            </div>

        </section>
        <h3>Técnica en Desarollo de Software 👩‍💻</h3>
        <p class="lead">Mi potencial radica en mi diversidad de conocimientos en distintos lenguajes y técnicas de
            programación.
            Siempre me encuentro en constante aprendizaje, especialización y creación de nuevos proyectos</p>
        <ul class="list-inline">
            <li class="list-inline-item"><span class="badge bg-warning text-dark" data-bs-toggle="collapse"
                    data-bs-target="#python">PYTHON</span></li>
            <li class="list-inline-item"><span class="badge bg-info text-dark" data-bs-toggle="collapse"
                    data-bs-target="#c_sharp">C#</span></li>
            <li class="list-inline-item"><span class="badge bg-danger text-dark" data-bs-toggle="collapse"
                    data-bs-target="#java">JAVA</span></li>
            <li class="list-inline-item"><span class="badge bg-primary text-dark" data-bs-toggle="collapse"
                    data-bs-target="#sql">SQL</span></li>
        </ul>
        <a class="btn btn-dark btn-sm p-3" href="{% static 'porfolio/cv_msol.pdf' %}" target="_blank"
            style="color:rgb(253, 225, 66)">Descarcar CV</a>

        <!-- <div id="python" class="collapse show">
                Prooooooximamente🐍🐍🐍
            </div>
            <div id="c_sharp" class="collapse show">
                Prooooooximamente ###
            </div>
            <div id="java" class="collapse show">
                Prooooooximamente☕☕☕
            </div>
            <div id="sql" class="collapse show">
                Prooooooximamente 🐬🐬
            </div> -->
</header>

porfolio/templates/componentes/navbar.html
{% load static %}

<!--Seccion NAVBAR-->
<nav class="navbar navbar-expand p-2 mb-3" style="background-color:rgb(22, 153, 92)">
    <div class="nav navbar-nav ms-auto">
        <a class="nav-item nav-link p-3" href="{% url 'home' %}" style="color:rgb(0, 0, 0); margin:0px 4px">HOME</a>
        <a class="nav-item nav-link p-3" href="{% url 'home' %}" style="color:rgb(0, 0, 0); margin:0px 4px">PROYECTOS</a>
        <a class="nav-item nav-link p-3" href="{% url 'contacto'  %}" style="color:rgb(0, 0, 0); margin:0px 4px">CONTACTOS</a>
        <a class="nav-item nav-link p-3" href="{% url 'blog:posts' %}" style="color:rgb(0, 0, 0); margin:0px 4px">BLOG</a>
        <a class="btn btn-dark btn-sm p-3" href="{% static 'porfolio/cv_msol.pdf' %}" target="_blank" style="color:rgb(253, 225, 66); margin:0px 4px; font-size: 15px;">Descarcar CV</a>
    </div>
</nav>

porfolio/templates/contacto.html
{% extends 'componentes/body.html'%}

<!--Sección CONTACTO - FORMULARIO-->
{% block titulo %} Contacto {% endblock %}

{% block contenido %}
<h2>Cotacto</h2>
<div.<div class="container">
    <p>Si te gustaría ponerte contacto conmigo me podés mandar un mensaje y con gusto re responderé en la brevedad!!
    </p>
    <form action="/contactar/" method="POST">
        {% csrf_token %}
        <div class="mb-3 mt-3">
            <label for="nombre" class="form-label" name="nombre">Nombre</label>
            <input type="text" class="form-control" placeholder="Nombre" name="nombre">
        </div>
        <div class="mb-3">
            <label for="asunto" class="form-label">Asunto</label>
            <input type="text" class="form-control" placeholder="Asunto" name="apellido">
        </div>
        <div class="mb-3">
            <label for="email" class="form-label">Email</label>
            <input type="email" class="form-control" placeholder="Email" name="Email">
        </div>
        <div class="mb-3">
            <label for="comment">Mensaje</label>
            <textarea class="form-control" rows="5" name="mensaje" style="resize:none;"></textarea>
        </div>
        <button type="submit" class="btn btn-warning">Enviar</button>
    </form>
{% endblock %}

porfolio/templates/home.html
{% extends 'componentes/body.html' %}

{% load static %}

{% block titulo %} Home {% endblock%}

{% block contenido %}
<!--Sección HEADER HOME-->
    {% include 'componentes/header.html'%}
    
<!--Sección PORFOLIO-->
    <div id='proyectos' class="row my-4 text-center">
        <h3 class="display-6 "> Proyectos realizados </h3>
        <hr>
        {% for p in proyectos %}
        <div class="col-md-4 p-4">
            <div class="card card-proyecto">
                <img class="card-img-top rounded-3" src="{{p.imagen.url}}" alt="Imagen sobre {{p.titulo}}">
                <div class="card-body">
                    <h4 class="card-title">{{p.titulo}}</h4>
                    <p class="card-text lead ">{{p.descripcion}}</p>
                    {% if p.url %}
                        <a href="{{p.url}}" class="btn btn-black bg-dark rounded-3 btn-sm  text-light" target="_black"> Repositorio GitHub</a>
                    {% endif%}
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    
{% endblock %}

porfolio/templates/inicio.html
{% extends 'componentes/body.html' %}

<!-- Sección INICIO-->
{% block titulo %} Inicio {% endblock%}

{% block contenido %}
    <div class="p-5" style="border-radius:20px; background-color: rgba(170, 115, 51, 0.438);">
            <h1 class="display-3">👋😄¡¡Hola te damos la bienvenida!! </h1>
            <br>
            <p class="lead" style="font-size:25px">Esta es una aplicación contruida con:</p>
            <ul class="list-inline">
                <li class="list-inline-item"><span class="badge bg-warning text-dark">Python 3.10.1</span></li>
                <li class="list-inline-item"><span class="badge bg-info text-dark">Django 4.0.4 </span></li>
                <li class="list-inline-item"><span class="badge bg-danger text-dark">Sqlite3</span></li>
            </ul>
            <hr class="my-2">
            <p style="font-weight: bold; font-size:17px">😉👇 Te invitamos a que nos conozcas y veas nuestro blog!
            </p>
            <p class="lead">
                <a class="btn btn-outline-dark btn-lg" style="background: rgb(230, 235, 105); color: rgb(0, 0, 0);" href="{% url 'home'%}" role="button">INGRESAR</a>
            </p>
    </div>
{% endblock %}